/**
 * Fetches the official Fivetran REST API OpenAPI spec and generates
 * src/api-catalog.ts with a typed array of all endpoints.
 *
 * Run: npm run generate-catalog
 */

import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const SPEC_URL =
  "https://fivetran.com/assets-docs/openapi/file_v1.json";

interface OpenAPISpec {
  paths: Record<
    string,
    Record<
      string,
      {
        summary?: string;
        tags?: string[];
        operationId?: string;
        parameters?: Array<{
          name: string;
          in: string;
          required?: boolean;
        }>;
        requestBody?: unknown;
      }
    >
  >;
}

interface CatalogEntry {
  method: string;
  path: string;
  summary: string;
  tag: string;
  pathParams: string[];
  queryParams: string[];
  hasBody: boolean;
}

const TAG_DESCRIPTIONS: Record<string, string> = {
  "Account Management": "Account-level info and settings",
  "Certificate Management": "SSL certificate and fingerprint approval",
  "Connection Management": "Connectors — create, configure, sync, pause, resume, delete",
  "Connection Schema Management": "Schema, table, and column configuration for connections",
  "Connector Metadata": "Available connector types and configuration schemas",
  "Connector SDK": "Custom connector SDK management",
  "Destination Management": "Data warehouse and lake destinations",
  "Group Management": "Groups (workspaces) — connectors, users, service accounts",
  "HVR Registrations": "HVR replication registrations",
  "Hybrid Deployment Agent Management": "On-premises deployment agent management",
  "Log Service": "Sync logs and log service configuration",
  "Private Link": "Private networking configuration (AWS/Azure/GCP)",
  "Proxy Agent Management": "Proxy agent configuration for private networks",
  "Role Management": "Roles and permissions",
  "System Key Management": "System API key management",
  "Team Management": "Teams — membership, groups, connections, permissions",
  "Transformation Management": "dbt transformations — create, run, manage",
  "Transformation Projects Management": "dbt project management",
  "User Management": "Users — invite, modify, delete, memberships",
  "Webhook Management": "Webhooks — create, test, manage notifications",
};

async function main() {
  console.log("Fetching Fivetran REST API spec...");
  const resp = await fetch(SPEC_URL);
  if (!resp.ok) {
    throw new Error(`Failed to fetch spec: ${resp.status} ${resp.statusText}`);
  }

  const spec: OpenAPISpec = await resp.json();
  const catalog: CatalogEntry[] = [];
  const tags = new Set<string>();

  for (const [path, methods] of Object.entries(spec.paths)) {
    // Collect path-level parameters
    const pathLevelParams = (methods as Record<string, unknown>).parameters as
      | Array<{ name: string; in: string }>
      | undefined;

    for (const [method, operation] of Object.entries(methods)) {
      if (method === "parameters" || method.startsWith("x-")) continue;
      if (typeof operation !== "object" || !operation) continue;

      const op = operation as {
        summary?: string;
        tags?: string[];
        operationId?: string;
        parameters?: Array<{ name: string; in: string; required?: boolean }>;
        requestBody?: unknown;
      };

      // Use summary, operationId, or skip
      const summary = op.summary ?? op.operationId ?? "";
      if (!summary) continue;

      const tag = op.tags?.[0] ?? "other";
      tags.add(tag);

      // Merge path-level and operation-level parameters
      const allParams = [...(pathLevelParams ?? []), ...(op.parameters ?? [])];

      const pathParams = allParams
        .filter((p) => p.in === "path")
        .map((p) => p.name);

      const queryParams = allParams
        .filter((p) => p.in === "query")
        .map((p) => p.name);

      const hasBody = !!op.requestBody;

      catalog.push({
        method: method.toUpperCase(),
        path,
        summary,
        tag,
        pathParams,
        queryParams,
        hasBody,
      });
    }
  }

  // Sort by tag, then path, then method
  catalog.sort((a, b) => {
    if (a.tag !== b.tag) return a.tag.localeCompare(b.tag);
    if (a.path !== b.path) return a.path.localeCompare(b.path);
    return a.method.localeCompare(b.method);
  });

  const sortedTags = [...tags].sort();

  // Generate TypeScript file
  const output = `// Auto-generated by scripts/generate-catalog.ts — do not edit manually
// Source: ${SPEC_URL}
// Generated: ${new Date().toISOString()}

import type { CatalogEntry } from "./types.js";

export const API_CATALOG: CatalogEntry[] = ${JSON.stringify(catalog, null, 2)} as const;

export const ALL_TAGS: string[] = ${JSON.stringify(sortedTags)};

export const TAG_DESCRIPTIONS: Record<string, string> = ${JSON.stringify(TAG_DESCRIPTIONS, null, 2)};
`;

  const __dirname = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(__dirname, "../src/api-catalog.ts");
  writeFileSync(outPath, output, "utf-8");

  console.log(`Generated ${outPath}`);
  console.log(`  ${catalog.length} endpoints across ${sortedTags.length} tags`);
  console.log(`  Tags: ${sortedTags.join(", ")}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
