// Auto-generated by scripts/generate-catalog.ts — do not edit manually
// Source: https://fivetran.com/assets-docs/openapi/file_v1.json
// Generated: 2026-03-10T22:15:14.222Z

import type { CatalogEntry } from "./types.js";

export const API_CATALOG: CatalogEntry[] = [
  {
    "method": "GET",
    "path": "/v1/account/info",
    "summary": "Get Account Info from the API Key",
    "tag": "Account Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/certificates",
    "summary": "(Deprecated) Approve a Certificate",
    "tag": "Certificate Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/connections/{connectionId}/certificates",
    "summary": "List Certificates Approved for the Connection",
    "tag": "Certificate Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/connections/{connectionId}/certificates",
    "summary": "Approve a Certificate for the Connection",
    "tag": "Certificate Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/connections/{connectionId}/certificates/{hash}",
    "summary": "Revoke Connection Certificate",
    "tag": "Certificate Management",
    "pathParams": [
      "connectionId",
      "hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/connections/{connectionId}/certificates/{hash}",
    "summary": "Retrieve Connection Certificate Details",
    "tag": "Certificate Management",
    "pathParams": [
      "connectionId",
      "hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/connections/{connectionId}/fingerprints",
    "summary": "List Fingerprints Approved for the Connection",
    "tag": "Certificate Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/connections/{connectionId}/fingerprints",
    "summary": "Approve a Fingerprint for the Connection",
    "tag": "Certificate Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/connections/{connectionId}/fingerprints/{hash}",
    "summary": "Revoke Connection Fingerprint",
    "tag": "Certificate Management",
    "pathParams": [
      "connectionId",
      "hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/connections/{connectionId}/fingerprints/{hash}",
    "summary": "Retrieve Connection Fingerprint Details",
    "tag": "Certificate Management",
    "pathParams": [
      "connectionId",
      "hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/destinations/{destinationId}/certificates",
    "summary": "List Certificates Approved for the Destination",
    "tag": "Certificate Management",
    "pathParams": [
      "destinationId"
    ],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/destinations/{destinationId}/certificates",
    "summary": "Approve a Certificate for the Destination",
    "tag": "Certificate Management",
    "pathParams": [
      "destinationId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/destinations/{destinationId}/certificates/{hash}",
    "summary": "Revoke Destination Certificate",
    "tag": "Certificate Management",
    "pathParams": [
      "destinationId",
      "hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/destinations/{destinationId}/certificates/{hash}",
    "summary": "Retrieve Destination Certificate Details",
    "tag": "Certificate Management",
    "pathParams": [
      "destinationId",
      "hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/destinations/{destinationId}/fingerprints",
    "summary": "List Fingerprints Approved for the Destination",
    "tag": "Certificate Management",
    "pathParams": [
      "destinationId"
    ],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/destinations/{destinationId}/fingerprints",
    "summary": "Approve a Fingerprint for the Destination",
    "tag": "Certificate Management",
    "pathParams": [
      "destinationId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/destinations/{destinationId}/fingerprints/{hash}",
    "summary": "Revoke Destination Fingerprint",
    "tag": "Certificate Management",
    "pathParams": [
      "destinationId",
      "hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/destinations/{destinationId}/fingerprints/{hash}",
    "summary": "Retrieve Destination Fingerprint Details",
    "tag": "Certificate Management",
    "pathParams": [
      "destinationId",
      "hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/connections",
    "summary": "List All Connections",
    "tag": "Connection Management",
    "pathParams": [],
    "queryParams": [
      "group_id",
      "schema",
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/connections",
    "summary": "Create a Connection",
    "tag": "Connection Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/connections/{connectionId}",
    "summary": "Delete a Connection",
    "tag": "Connection Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/connections/{connectionId}",
    "summary": "Retrieve Connection Details",
    "tag": "Connection Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/connections/{connectionId}",
    "summary": "Update a Connection",
    "tag": "Connection Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/connections/{connectionId}/connect-card",
    "summary": "Create a Connect Card",
    "tag": "Connection Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/connections/{connectionId}/resync",
    "summary": "Re-sync Connection Data (Historical Sync)",
    "tag": "Connection Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/connections/{connectionId}/state",
    "summary": "Retrieve Connection State",
    "tag": "Connection Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/connections/{connectionId}/state",
    "summary": "Update a Connection State",
    "tag": "Connection Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/connections/{connectionId}/sync",
    "summary": "Sync Connection Data",
    "tag": "Connection Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/connections/{connectionId}/test",
    "summary": "Run Connection Setup Tests",
    "tag": "Connection Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/connections/{connectionId}/schemas",
    "summary": "Retrieve a Connection Schema Config",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/connections/{connectionId}/schemas",
    "summary": "Update a Connection Schema Config",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/connections/{connectionId}/schemas",
    "summary": "Set Up a New Connection Schema Config",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/connections/{connectionId}/schemas/{schema}/tables/{table}/columns",
    "summary": "Retrieve Source Table Columns Config",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId",
      "schema",
      "table"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/connections/{connectionId}/schemas/{schemaName}",
    "summary": "Update a Connection Database Schema Config",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId",
      "schemaName"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "PATCH",
    "path": "/v1/connections/{connectionId}/schemas/{schemaName}/tables/{tableName}",
    "summary": "Update a Connection Table Config",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId",
      "schemaName",
      "tableName"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/connections/{connectionId}/schemas/{schemaName}/tables/{tableName}/columns/{columnName}",
    "summary": "Drop a Blocked Column From the Destination",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId",
      "schemaName",
      "tableName",
      "columnName"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/connections/{connectionId}/schemas/{schemaName}/tables/{tableName}/columns/{columnName}",
    "summary": "Update a Connection Column Config",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId",
      "schemaName",
      "tableName",
      "columnName"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/connections/{connectionId}/schemas/drop-columns",
    "summary": "Drop Blocked Columns from the Destination.",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/connections/{connectionId}/schemas/reload",
    "summary": "Reload a Connection Schema Config",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/connections/{connectionId}/schemas/tables/resync",
    "summary": "Re-sync Connection Table Data",
    "tag": "Connection Schema Management",
    "pathParams": [
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/metadata/connector-types",
    "summary": "Retrieve Source Metadata",
    "tag": "Connector Metadata",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/metadata/connector-types/{service}",
    "summary": "Retrieve Connector Configuration Metadata",
    "tag": "Connector Metadata",
    "pathParams": [
      "service"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/connector-sdk/packages",
    "summary": "List All Connector SDK Packages",
    "tag": "Connector SDK Package Resource",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/connector-sdk/packages",
    "summary": "Create Connector SDK Package",
    "tag": "Connector SDK Package Resource",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/connector-sdk/packages/{package_id}",
    "summary": "Delete Connector SDK Package",
    "tag": "Connector SDK Package Resource",
    "pathParams": [
      "package_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/connector-sdk/packages/{package_id}",
    "summary": "Retrieve Connector SDK Package Details",
    "tag": "Connector SDK Package Resource",
    "pathParams": [
      "package_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/connector-sdk/packages/{package_id}",
    "summary": "Update Connector SDK Package",
    "tag": "Connector SDK Package Resource",
    "pathParams": [
      "package_id"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/connector-sdk/packages/{package_id}/download",
    "summary": "Download Connector SDK Package",
    "tag": "Connector SDK Package Resource",
    "pathParams": [
      "package_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/destinations",
    "summary": "List All Destinations Within Account",
    "tag": "Destination Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/destinations",
    "summary": "Create a Destination",
    "tag": "Destination Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/destinations/{destinationId}",
    "summary": "Delete a Destination",
    "tag": "Destination Management",
    "pathParams": [
      "destinationId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/destinations/{destinationId}",
    "summary": "Retrieve Destination Details",
    "tag": "Destination Management",
    "pathParams": [
      "destinationId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/destinations/{destinationId}",
    "summary": "Update a Destination",
    "tag": "Destination Management",
    "pathParams": [
      "destinationId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/destinations/{destinationId}/test",
    "summary": "Run Destination Setup Tests",
    "tag": "Destination Management",
    "pathParams": [
      "destinationId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/groups",
    "summary": "List All Destinations within Account",
    "tag": "Group Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/groups",
    "summary": "Create a Group",
    "tag": "Group Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/groups/{groupId}",
    "summary": "Delete a Group",
    "tag": "Group Management",
    "pathParams": [
      "groupId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/groups/{groupId}",
    "summary": "Retrieve Group Details",
    "tag": "Group Management",
    "pathParams": [
      "groupId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/groups/{groupId}",
    "summary": "Update a Group",
    "tag": "Group Management",
    "pathParams": [
      "groupId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/groups/{groupId}/connections",
    "summary": "List All Connections within a Group",
    "tag": "Group Management",
    "pathParams": [
      "groupId"
    ],
    "queryParams": [
      "schema",
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/groups/{groupId}/public-key",
    "summary": "Retrieve Group Public SSH Key",
    "tag": "Group Management",
    "pathParams": [
      "groupId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/groups/{groupId}/service-account",
    "summary": "Retrieve Group Service Account",
    "tag": "Group Management",
    "pathParams": [
      "groupId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/groups/{groupId}/users",
    "summary": "List All Users within a Group",
    "tag": "Group Management",
    "pathParams": [
      "groupId"
    ],
    "queryParams": [
      "cursor",
      "limit",
      "active"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/groups/{groupId}/users",
    "summary": "Add a User to a Group",
    "tag": "Group Management",
    "pathParams": [
      "groupId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/groups/{groupId}/users/{userId}",
    "summary": "Remove a User from a Group",
    "tag": "Group Management",
    "pathParams": [
      "groupId",
      "userId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/hvr/register-hub",
    "summary": "Register Hub",
    "tag": "HVR Registrations Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/hybrid-deployment-agents",
    "summary": "List Hybrid Deployment Agents",
    "tag": "Hybrid Deployment Agent Management",
    "pathParams": [],
    "queryParams": [
      "groupId",
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/hybrid-deployment-agents",
    "summary": "Create a Hybrid Deployment Agent",
    "tag": "Hybrid Deployment Agent Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/hybrid-deployment-agents/{agentId}",
    "summary": "Delete a Hybrid Deployment Agent",
    "tag": "Hybrid Deployment Agent Management",
    "pathParams": [
      "agentId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/hybrid-deployment-agents/{agentId}",
    "summary": "Returns Hybrid Deployment Agent Details",
    "tag": "Hybrid Deployment Agent Management",
    "pathParams": [
      "agentId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/hybrid-deployment-agents/{agentId}/re-auth",
    "summary": "Regenerate Authentication Keys",
    "tag": "Hybrid Deployment Agent Management",
    "pathParams": [
      "agentId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/hybrid-deployment-agents/{agentId}/reset-credentials",
    "summary": "Reset Agent Credentials",
    "tag": "Hybrid Deployment Agent Management",
    "pathParams": [
      "agentId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/external-logging",
    "summary": "List All Log Services within Account",
    "tag": "Log Service Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/external-logging",
    "summary": "Create a Group Log Service",
    "tag": "Log Service Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/external-logging/{logId}",
    "summary": "Delete a Group Log Service",
    "tag": "Log Service Management",
    "pathParams": [
      "logId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/external-logging/{logId}",
    "summary": "Retrieve Group Log Service Details",
    "tag": "Log Service Management",
    "pathParams": [
      "logId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/external-logging/{logId}",
    "summary": "Update a Group Log Service",
    "tag": "Log Service Management",
    "pathParams": [
      "logId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/external-logging/{logId}/test",
    "summary": "Run Group Log Service Setup Tests",
    "tag": "Log Service Management",
    "pathParams": [
      "logId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/v1/external-logging/account",
    "summary": "Delete Account Log Service",
    "tag": "Log Service Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/external-logging/account",
    "summary": "Retrieve Account Log Service",
    "tag": "Log Service Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/external-logging/account",
    "summary": "Update Account Log Service",
    "tag": "Log Service Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/external-logging/account",
    "summary": "Create Account Log Service",
    "tag": "Log Service Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/private-links",
    "summary": "List All Private Links",
    "tag": "Private Link Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/private-links",
    "summary": "Create a Private Link",
    "tag": "Private Link Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/private-links/{privateLinkId}",
    "summary": "Delete a Private Link",
    "tag": "Private Link Management",
    "pathParams": [
      "privateLinkId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/private-links/{privateLinkId}",
    "summary": "Retrieve Private Link Details",
    "tag": "Private Link Management",
    "pathParams": [
      "privateLinkId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/private-links/{privateLinkId}",
    "summary": "Update a Private Link",
    "tag": "Private Link Management",
    "pathParams": [
      "privateLinkId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/proxy",
    "summary": "List all Proxy Agents",
    "tag": "Proxy Agent Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/proxy",
    "summary": "Create a Proxy Agent",
    "tag": "Proxy Agent Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/proxy/{agentId}",
    "summary": "Delete a Proxy Agent",
    "tag": "Proxy Agent Management",
    "pathParams": [
      "agentId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/proxy/{agentId}",
    "summary": "Retrieve Proxy Agent Details",
    "tag": "Proxy Agent Management",
    "pathParams": [
      "agentId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/proxy/{agentId}/connections",
    "summary": "List All Connections Attached to the Proxy Agent",
    "tag": "Proxy Agent Management",
    "pathParams": [
      "agentId"
    ],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/proxy/{agentId}/regenerate-secrets",
    "summary": "Regenerate Secrets for Proxy Agent",
    "tag": "Proxy Agent Management",
    "pathParams": [
      "agentId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/public/connector-types",
    "summary": "Retrieve Source Metadata Public Endpoint",
    "tag": "Public Endpoints",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/roles",
    "summary": "List all roles",
    "tag": "Role Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/system-keys",
    "summary": "List All System Keys",
    "tag": "System Key Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/system-keys",
    "summary": "Create a System Key",
    "tag": "System Key Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/system-keys/{keyId}",
    "summary": "Delete a System Key",
    "tag": "System Key Management",
    "pathParams": [
      "keyId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/system-keys/{keyId}",
    "summary": "Retrieve System Key Details",
    "tag": "System Key Management",
    "pathParams": [
      "keyId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/system-keys/{keyId}",
    "summary": "Update a System Key",
    "tag": "System Key Management",
    "pathParams": [
      "keyId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/system-keys/{keyId}/rotate",
    "summary": "Rotate a System Key",
    "tag": "System Key Management",
    "pathParams": [
      "keyId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/teams",
    "summary": "List All Teams",
    "tag": "Team Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/teams",
    "summary": "Create a Team",
    "tag": "Team Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/teams/{teamId}",
    "summary": "Delete a Team",
    "tag": "Team Management",
    "pathParams": [
      "teamId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/teams/{teamId}",
    "summary": "Retrieve Team Details",
    "tag": "Team Management",
    "pathParams": [
      "teamId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/teams/{teamId}",
    "summary": "Update a Team",
    "tag": "Team Management",
    "pathParams": [
      "teamId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/teams/{teamId}/connections",
    "summary": "List All Connection Memberships",
    "tag": "Team Management",
    "pathParams": [
      "teamId"
    ],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/teams/{teamId}/connections",
    "summary": "Add Connection Membership",
    "tag": "Team Management",
    "pathParams": [
      "teamId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/teams/{teamId}/connections/{connectionId}",
    "summary": "Delete Connection Membership",
    "tag": "Team Management",
    "pathParams": [
      "teamId",
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/teams/{teamId}/connections/{connectionId}",
    "summary": "Retrieve Connection Membership",
    "tag": "Team Management",
    "pathParams": [
      "teamId",
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/teams/{teamId}/connections/{connectionId}",
    "summary": "Update Connection Membership",
    "tag": "Team Management",
    "pathParams": [
      "teamId",
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/teams/{teamId}/groups",
    "summary": "List All Group Memberships",
    "tag": "Team Management",
    "pathParams": [
      "teamId"
    ],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/teams/{teamId}/groups",
    "summary": "Add Group Membership",
    "tag": "Team Management",
    "pathParams": [
      "teamId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/teams/{teamId}/groups/{groupId}",
    "summary": "Delete Group Membership",
    "tag": "Team Management",
    "pathParams": [
      "teamId",
      "groupId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/teams/{teamId}/groups/{groupId}",
    "summary": "Retrieve Group Membership Details",
    "tag": "Team Management",
    "pathParams": [
      "teamId",
      "groupId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/teams/{teamId}/groups/{groupId}",
    "summary": "Update Group Membership",
    "tag": "Team Management",
    "pathParams": [
      "teamId",
      "groupId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/teams/{teamId}/role",
    "summary": "Delete Team from Account",
    "tag": "Team Management",
    "pathParams": [
      "teamId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/teams/{teamId}/users",
    "summary": "List All User Memberships",
    "tag": "Team Management",
    "pathParams": [
      "teamId"
    ],
    "queryParams": [
      "cursor",
      "limit",
      "active"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/teams/{teamId}/users",
    "summary": "Add a User to the Team",
    "tag": "Team Management",
    "pathParams": [
      "teamId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/teams/{teamId}/users/{userId}",
    "summary": "Delete a User from a Team",
    "tag": "Team Management",
    "pathParams": [
      "teamId",
      "userId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/teams/{teamId}/users/{userId}",
    "summary": "Retrieve User Membership in a Team",
    "tag": "Team Management",
    "pathParams": [
      "teamId",
      "userId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/teams/{teamId}/users/{userId}",
    "summary": "Update a User Membership",
    "tag": "Team Management",
    "pathParams": [
      "teamId",
      "userId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/transformations",
    "summary": "List all Transformations",
    "tag": "Transformation Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit",
      "group_id",
      "project_id",
      "type"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/transformations",
    "summary": "Create a Transformation",
    "tag": "Transformation Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/transformations/{transformationId}",
    "summary": "Delete a Transformation",
    "tag": "Transformation Management",
    "pathParams": [
      "transformationId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/transformations/{transformationId}",
    "summary": "Retrieve Transformation Details",
    "tag": "Transformation Management",
    "pathParams": [
      "transformationId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/transformations/{transformationId}",
    "summary": "Update a Transformation",
    "tag": "Transformation Management",
    "pathParams": [
      "transformationId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/transformations/{transformationId}/cancel",
    "summary": "Cancel Running Transformation",
    "tag": "Transformation Management",
    "pathParams": [
      "transformationId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/transformations/{transformationId}/run",
    "summary": "Run Transformation",
    "tag": "Transformation Management",
    "pathParams": [
      "transformationId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/transformations/{transformationId}/upgrade",
    "summary": "Upgrade Transformation Package",
    "tag": "Transformation Management",
    "pathParams": [
      "transformationId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/transformations/package-metadata",
    "summary": "List All Quickstart Package Metadata",
    "tag": "Transformation Management",
    "pathParams": [],
    "queryParams": [
      "service",
      "name",
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/transformations/package-metadata/{package_definition_id}",
    "summary": "Retrieve a Quickstart Package Metadata Details",
    "tag": "Transformation Management",
    "pathParams": [
      "package_definition_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/transformation-projects",
    "summary": "List all Transformation Projects",
    "tag": "Transformation Projects Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/transformation-projects",
    "summary": "Create Transformation Project",
    "tag": "Transformation Projects Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/transformation-projects/{projectId}",
    "summary": "Delete Transformation Project",
    "tag": "Transformation Projects Management",
    "pathParams": [
      "projectId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/transformation-projects/{projectId}",
    "summary": "Retrieve Transformation Project Details",
    "tag": "Transformation Projects Management",
    "pathParams": [
      "projectId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/transformation-projects/{projectId}",
    "summary": "Update Transformation Project",
    "tag": "Transformation Projects Management",
    "pathParams": [
      "projectId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/transformation-projects/{projectId}/test",
    "summary": "Test Transformation Project",
    "tag": "Transformation Projects Management",
    "pathParams": [
      "projectId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/users",
    "summary": "List All Users",
    "tag": "User Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit",
      "active"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/users",
    "summary": "Invite a User",
    "tag": "User Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/users/{id}",
    "summary": "Delete a User",
    "tag": "User Management",
    "pathParams": [
      "id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/users/{userId}",
    "summary": "Retrieve a User Details",
    "tag": "User Management",
    "pathParams": [
      "userId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/users/{userId}",
    "summary": "Update a User",
    "tag": "User Management",
    "pathParams": [
      "userId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/users/{userId}/connections",
    "summary": "List All Connection Memberships",
    "tag": "User Management",
    "pathParams": [
      "userId"
    ],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/users/{userId}/connections",
    "summary": "Add a Connection Membership",
    "tag": "User Management",
    "pathParams": [
      "userId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/users/{userId}/connections/{connectionId}",
    "summary": "Delete Connection Membership",
    "tag": "User Management",
    "pathParams": [
      "userId",
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/users/{userId}/connections/{connectionId}",
    "summary": "Retrieve Connection Membership",
    "tag": "User Management",
    "pathParams": [
      "userId",
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/users/{userId}/connections/{connectionId}",
    "summary": "Update Connection Membership",
    "tag": "User Management",
    "pathParams": [
      "userId",
      "connectionId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "GET",
    "path": "/v1/users/{userId}/groups",
    "summary": "List All Group Memberships",
    "tag": "User Management",
    "pathParams": [
      "userId"
    ],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/v1/users/{userId}/groups",
    "summary": "Add Group Membership",
    "tag": "User Management",
    "pathParams": [
      "userId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/users/{userId}/groups/{groupId}",
    "summary": "Delete Group Membership",
    "tag": "User Management",
    "pathParams": [
      "userId",
      "groupId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/users/{userId}/groups/{groupId}",
    "summary": "Retrieve Group Membership Details",
    "tag": "User Management",
    "pathParams": [
      "userId",
      "groupId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/users/{userId}/groups/{groupId}",
    "summary": "Update Group Membership",
    "tag": "User Management",
    "pathParams": [
      "userId",
      "groupId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "DELETE",
    "path": "/v1/users/{userId}/role",
    "summary": "Delete Account Role",
    "tag": "User Management",
    "pathParams": [
      "userId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/webhooks",
    "summary": "List all Webhooks",
    "tag": "Webhook Management",
    "pathParams": [],
    "queryParams": [
      "cursor",
      "limit"
    ],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/v1/webhooks/{webhookId}",
    "summary": "Delete a Webhook",
    "tag": "Webhook Management",
    "pathParams": [
      "webhookId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/v1/webhooks/{webhookId}",
    "summary": "Retrieve Webhook Details",
    "tag": "Webhook Management",
    "pathParams": [
      "webhookId"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/v1/webhooks/{webhookId}",
    "summary": "Update a Webhook",
    "tag": "Webhook Management",
    "pathParams": [
      "webhookId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/webhooks/{webhookId}/test",
    "summary": "Test a Webhook",
    "tag": "Webhook Management",
    "pathParams": [
      "webhookId"
    ],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/webhooks/account",
    "summary": "Create an Account Webhook",
    "tag": "Webhook Management",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true
  },
  {
    "method": "POST",
    "path": "/v1/webhooks/group/{groupId}",
    "summary": "Create a Group Webhook",
    "tag": "Webhook Management",
    "pathParams": [
      "groupId"
    ],
    "queryParams": [],
    "hasBody": true
  }
] as const;

export const ALL_TAGS: string[] = ["Account Management","Certificate Management","Connection Management","Connection Schema Management","Connector Metadata","Connector SDK Package Resource","Destination Management","Group Management","HVR Registrations Management","Hybrid Deployment Agent Management","Log Service Management","Private Link Management","Proxy Agent Management","Public Endpoints","Role Management","System Key Management","Team Management","Transformation Management","Transformation Projects Management","User Management","Webhook Management"];

export const TAG_DESCRIPTIONS: Record<string, string> = {
  "Account Management": "Account-level info and settings",
  "Certificate Management": "SSL certificate and fingerprint approval",
  "Connection Management": "Connectors — create, configure, sync, pause, resume, delete",
  "Connection Schema Management": "Schema, table, and column configuration for connections",
  "Connector Metadata": "Available connector types and configuration schemas",
  "Connector SDK": "Custom connector SDK management",
  "Destination Management": "Data warehouse and lake destinations",
  "Group Management": "Groups (workspaces) — connectors, users, service accounts",
  "HVR Registrations": "HVR replication registrations",
  "Hybrid Deployment Agent Management": "On-premises deployment agent management",
  "Log Service": "Sync logs and log service configuration",
  "Private Link": "Private networking configuration (AWS/Azure/GCP)",
  "Proxy Agent Management": "Proxy agent configuration for private networks",
  "Role Management": "Roles and permissions",
  "System Key Management": "System API key management",
  "Team Management": "Teams — membership, groups, connections, permissions",
  "Transformation Management": "dbt transformations — create, run, manage",
  "Transformation Projects Management": "dbt project management",
  "User Management": "Users — invite, modify, delete, memberships",
  "Webhook Management": "Webhooks — create, test, manage notifications"
};
